[theme]
primaryColor = "#00A86B" # 제이드 그린
backgroundColor = "#FDFDFD" # 아주 밝은 그레이 또는 화이트
secondaryBackgroundColor = "#F0F2F6" # 사이드바 배경
textColor = "#31333F"

[server]
headless = true

[menuItems]
showGetHelp = false
showReportBug = false
